---
repos:
  - repo: https://github.com/lyz-code/yamlfix/
    rev: 1.9.0
    hooks:
      - id: yamlfix
        exclude: (.*.*/templates/.*.yaml|kubernetes/helm/application-charts/test-oh-std-lib/values.yaml)
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]
        exclude: package.lock.json
  ## tech debt to refactor google modules.
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.79.1
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_tflint
        args:
          - --args=--module
          - --args=--minimum-failure-severity=notice
          - --args=--config=.tflint.hcl
          - --args=--disable-rule terraform_naming_convention
          - --args=--disable-rule terraform_documented_outputs
          - --args=--disable-rule terraform_comment_syntax
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
        args: [--autofix]
      - id: mixed-line-ending
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.34.0
    hooks:
      - id: markdownlint-fix
